# This is a sample build configuration for Javascript.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:6.9.4

pipelines:
  default:
    - step:
        script:
          - npm install -g @angular/cli
          - npm install
          - ng build
          - cd functions
          - npm install
          - npm run lint
          - npm run build
  branches:
    develop:
      - step:
          script:
          - npm install -g @angular/cli
          - npm install
          - ng build
          - cd functions
          - npm install
          - npm run lint
          - npm run build
    master:
      - step:
          script:
          - npm install -g @angular/cli
          - npm install
          - ng build
          - cd functions
          - npm install
          - npm run lint
          - npm run build
